name: nakime
description: Keeps a record of system startup and shutdown times.
publish_to: 'none'
repository: https://github.com/omegaui/nakime

version: 0.0.1+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  gap: ^3.0.1
  flutter_acrylic: ^1.1.4
  google_fonts: ^6.2.1
  fl_chart: ^0.69.2
  intl: ^0.19.0
  package_info_plus: ^8.1.2
  lottie: ^3.2.0
  excel: ^4.0.6
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/