name: nakime
description: "Keeps a record of system startup and shutdown times."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  gap: ^3.0.1
  flutter_animate: ^4.5.2
  flutter_acrylic: ^1.1.4
  google_fonts: ^6.2.1
  fl_chart: ^0.69.2
  timeago: ^3.7.0
  intl: ^0.19.0
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icons/nakime.png"
    icon_size: 256

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
